# This config file only for develop
# This file is hugo-theme-jane demo-site config
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
baseURL = "https://dehong.rbind.io/"
 title = "光阴的故事"
enableRobotsTXT = true
enableEmoji = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 5                                              # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = "德宏"            # default: author.name ↓        # 默认为下面配置的author.name ↓
# uglyURLs = true

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
pygmentsUseClasses = true # Use CSS classes to format highlighted code
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

## language support en / zh / other... translations present in i18n/
defaultContentLanguage = "zh"           # Default language to use
[languages.zh]
languageCode = "zh"
[[menu.main]]             # config your menu              # 配置目录
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  url = "/about/"



[author]                  # essential                     # 必需
  name = "德宏"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  # uglyURLs = true          # You must set true after use uglyURLs in site (above). because $.Site.UglyURLs can not import.
  since = "2017"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = ""        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","jane"]
  description = "Hugo theme jane example site."

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 10

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]             # 是否使用bootcdn(@Deprecated: 请使用[params.publicCDN])
  mathjax = true          # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）

  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  #  changyanAppid = "cytkoYA6X"        # Changyan app id             # 畅言
  #  changyanAppkey = "prod_1d5fe5e02011caa6d27a611c497b08e6"       # Changyan app key
  tencent_analytics = ""    # Tencent Analytics
  baidu_push = false        # baidu push                  # 百度
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['custom.js']             # if ['custom.js'], load '/static/js/custom.js' file

  # enable 'fork me on github', https://blog.github.com/2008-12-19-github-ribbons/
   # forkMeOnGithub = "https://github.com/xianmin/hugo-theme-jane"

  #  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
   #   enable = false
   #   jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
   #   slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'

  [params.reward]                                         # 文章打赏
    enable = true
    wechat = "/image/weixin.jpg"           # 微信二维码
    alipay = "/image/zhifubao.jpg"           # 支付宝二维码

  [params.social]                                         # 社交链接
            a-email = "mailto:1126714486@qq.com"
            b-stack-overflow = "http://localhost:1313"
            # c-twitter = "http://localhost:1313"
            # d-facebook = "http://localhost:1313"
            # e-linkedin = "http://localhost:1313"
            #  f-google = "http://localhost:1313"
            g-github = "https://github.com/wdhjyr"
            h-weibo = "http://localhost:1313"
            i-zhihu = "http://localhost:1313"
            j-douban = "https://www.douban.com/people/wdh66/"
            # k-pocket = "http://localhost:1313"
            # l-tumblr = "http://localhost:1313"
            # m-instagram = "http://localhost:1313"
            # n-gitlab = "http://en.xianmin.org/hugo-theme-jane/"
            # o-goodreads = "http://en.xianmin.org/hugo-theme-jane/"
